### ISSUE TITLE
Blocking calls / OTGW Serial connection drops on configuration of SAT

### ISSUE THREAD

**Issue by ronaldt80** [Alexwijn/SAT#73]
Since a few months changing the configuration of SAT causes the serial connection of OTGW to break. A full restart of HA is required to solve this and get the integration back up and running.

Also during normal start up of HA there are blocking calls in the log which seem triggered by OTGW / Serial connection through SAT. Not completely clear to me where the issue lies (OTGW library or SAT) but perhaps you have an idea? Happy to do some further debugging.

```
2024-12-29 11:33:06.893 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback SerialTransport._call_connection_lost() (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 54, in raise_for_blocking_call
    integration_frame = get_integration_frame()
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 113, in get_integration_frame
    raise MissingIntegrationFrame
homeassistant.helpers.frame.MissingIntegrationFrame
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/serial_asyncio/__init__.py", line 417, in _call_connection_lost
    self._serial.close()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/serial/urlhandler/protocol_socket.py", line 104, in close
    time.sleep(0.3)
    ~~~~~~~~~~^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<4 lines>...
        kwargs=kwargs,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 96, in raise_for_blocking_call
    raise RuntimeError(  # noqa: TRY200
    ...<7 lines>...
    )
RuntimeError: Caught blocking call to sleep with args (0.3,) in /usr/local/lib/python3.13/site-packages/serial/urlhandler/protocol_socket.py, line 104: time.sleep(0.3) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep
2024-12-29 11:35:14.585 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback SerialTransport._call_connection_lost() (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 54, in raise_for_blocking_call
    integration_frame = get_integration_frame()
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 113, in get_integration_frame
    raise MissingIntegrationFrame
homeassistant.helpers.frame.MissingIntegrationFrame
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/serial_asyncio/__init__.py", line 417, in _call_connection_lost
    self._serial.close()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/serial/urlhandler/protocol_socket.py", line 104, in close
    time.sleep(0.3)
    ~~~~~~~~~~^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<4 lines>...
        kwargs=kwargs,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 96, in raise_for_blocking_call
    raise RuntimeError(  # noqa: TRY200
    ...<7 lines>...
    )
RuntimeError: Caught blocking call to sleep with args (0.3,) in /usr/local/lib/python3.13/site-packages/serial/urlhandler/protocol_socket.py, line 104: time.sleep(0.3) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep
2024-12-29 11:35:17.562 ERROR (MainThread) [pyotgw.pyotgw] Timed out waiting for command: MM, value: -.
```

**Comment by ronaldt80** [comment]
Whilst on the August version a restart of HA resolved the issues on the latest develop this does not resolve anything. For the time being rolled back to end of August dev version.

**Comment by Alexwijn** [comment]
I just updated the `pyotgw` library, see if that helps. The serial coordinator hasn't been changed for a while now.

**Comment by ronaldt80** [comment]
Thanks will try

**Comment by ronaldt80** [comment]
Thanks, it works albeit that the connection does not survive a reconfig or reload of the integration. Only a reboot of HA Core helps.
